export const GET_MOVIES = 'GET_MOVIES';
export const CHANGE_SORT = 'CHANGE_SORT';
export const CHANGE_FILTER = 'CHANGE_FILTER';

export const GET_MOVIE_DETAILS = 'GET_MOVIE_DETAILS';
export const RESET_MOVIE_DETAILS = 'RESET_MOVIE_DETAILS';

export const ADD_MOVIE = 'ADD_MOVIE';
export const EDIT_MOVIE = 'EDIT_MOVIE';
export const DELETE_MOVIE = 'DELETE_MOVIE';

export const OPEN_ADD_MOVIE_MODAL = 'OPEN_ADD_MOVIE_MODAL';
export const CLOSE_ADD_MOVIE_MODAL = 'CLOSE_ADD_MOVIE_MODAL';

export const OPEN_DELETE_MOVIE_MODAL = 'OPEN_DELETE_MOVIE_MODAL';
export const CLOSE_DELETE_MOVIE_MODAL = 'CLOSE_DELETE_MOVIE_MODAL';

export const OPEN_EDIT_MOVIE_MODAL = 'OPEN_EDIT_MOVIE_MODAL';
export const CLOSE_EDIT_MOVIE_MODAL = 'CLOSE_EDIT_MOVIE_MODAL';
